### ISSUE TITLE
Error when ctx.options.map is being used in postcss.config.js

### ISSUE THREAD

**Issue by ikornienko** [webpack-contrib/postcss-loader#497]
- Operating System: macOS Catalina
- Node Version: 14.15.1
- NPM Version: 6.14.8
- webpack Version: 4.42.1
- postcss-loader Version: 4.0.4

### Expected Behavior

No failure with the valid `postcss.config.js`.

### Actual Behavior

Seeing an error

```
Module build failed (from ./node_modules/gatsby-plugin-postcss/node_modules/postcss-loader/dist/cjs.js):
TypeError: Cannot read property 'map' of undefined
    at Object.module.exports [as config] (project_dir/postcss.config.js:84:20)
    at loadConfig (project_dir/node_modules/gatsby-plugin-postcss/node_modules/postcss-loader/dist/utils.js:89:28)
    at async Object.loader (project_dir/node_modules/gatsby-plugin-postcss/node_modules/postcss-loader/dist/index.js:53:22)
```

### Code
`postcss.config.js` (especially line `84` mentioned in the error) has a config 

```js
module.exports = (ctx) => ({
  map: ctx.options.map,  // this one is line 84
  plugins: [
    ...
```

It's a valid syntax as specified in [postcss-cli docs](https://github.com/postcss/postcss-cli#context), and `postcss-cli` works fine on it, only when this config is being loaded by `postcss-loader` in the context of `gatsby-plugin-postcss` then it fails.

### Additional Context

It happens during the Gatsby build, when [gatsby-plugin-postcss](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-postcss) uses `postcss-loader` to read the config. I have NOT opened an issue with `gatsby-plugin-postcss`. The project is using `gatsby-plugin-postcss` version `3.1.0`.

**Comment by ikornienko** [comment]
Not sure if it can be related to #480 because a different loader is now being used.

**Comment by evilebottnawi** [comment]
> It's a valid syntax as specified in postcss-cli docs, and postcss-cli works fine on it, only when this config is being loaded by postcss-loader in the context of gatsby-plugin-postcss then it fails.

We don't have compatibility with webpack-cli due it was abandoned a long time, I will try to fix it

**Comment by evilebottnawi** [comment]
Also I think you need to open an issue in `postcss-cli` repo, because many things are really weird and I don't want to implement them here:
- https://github.com/postcss/postcss-cli/blob/master/index.js#L51 - overriding `process.env.NODE_ENV` is the very very very bad idea in vendor code, it is unsafe
- https://github.com/postcss/postcss-cli/blob/master/index.js#L176 - why? what if I need something more, for example `name` or `root` https://nodejs.org/api/path.html#path_path_parse_path, so we pass it as string
- https://github.com/postcss/postcss-cli/blob/master/index.js#L29 - why you need `require` something if the config file can override it, it reduces performance and it is weird
- https://github.com/postcss/postcss-cli/blob/master/index.js#L30 - default values is another

But I can pass `postcssOptions` from loader to your config for keeping some compatibility

**Comment by ikornienko** [comment]
@evilebottnawi thank you for the response and a light speed fix + release! The concerns you bring about `postcss-cli` are indeed disturbing. I don't have all the context, TBH I haven't worked with `postcss-cli` too close. Just happened to be helping on a project that actively uses it, and on that project the attempt to upgrade `gatsby-plugin-postcss` broke the build because of the issue you just fixed :)

Thank you again for such an outstanding project maintenance discipline with this quick fix!
