### ISSUE TITLE
postcss-loader shows error while compile this style grid-column: 1/-1;  

### ISSUE THREAD

**Issue by manikandanm1757** [webpack-contrib/postcss-loader#506]
postcss-loader throws error while compile this line
**grid-column: 1/-1;**  

but it works when we add space between the slash like below.
**grid-column: 1 / -1;**

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

Please open an error in plugin where you handle grid, we don't touch your code
