### ISSUE TITLE
typeError: loader._compilation.applyPluginsWaterfall is not a function

### ISSUE THREAD

**Issue by rihannarickeminem** [webpack-contrib/postcss-loader#693]
`Module build failed (from ../node_modules/postcss-loader/index.js): TypeError: loader._compilation.applyPluginsWaterfall is not a function`
constantly getting this error on build. cant perform build for project
postcss-loader v 3

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

We don't have `applyPluginsWaterfall` function

Also v3 is not supported
